name: Publish Kotlin artifacts
description: "Publish Kotlin artifacts"
inputs:
  gradle-cache-encryption-key:
    description: 'The encryption key for the Gradle cache.'
    required: false
  tests:
    description: 'Run tests'
    default: 'false'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-encryption-key: ${{ inputs.gradle-cache-encryption-key }}
        gradle-home-cache-cleanup: true
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
        add-job-summary-as-pr-comment: on-failure

    - name: Publish release
      shell: bash
      if: "github.event_name == 'release'"
      run: ./gradlew clean publish ${{ inputs.tests && 'check' || '-x check -x test' }} -Pdeploy.kotlin=true -Pdeploy.native=false -Pdeploy.version=${{ github.event.release.tag_name }} --console=plain --info --configure-on-demand --parallel --build-cache --configuration-cache

    - name: Set outputs
      id: vars
      shell: bash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Publish snapshot
      shell: bash
      if: "github.event_name != 'release'"
      run: ./gradlew clean publish ${{ inputs.tests && 'check' || '-x check -x test' }} -Pdeploy.kotlin=true -Pdeploy.native=false -Pdeploy.version=${{ steps.vars.outputs.sha_short }}-dev --console=plain --info --configure-on-demand --parallel --build-cache --configuration-cache
