name: Deploy on Ubuntu
description: "Deploy on Ubuntu"
inputs:
  snapshot-repo-url:
    description: "The URL of the maven repository"
    required: false
  release-repo-url:
    description: "The URL of the maven repository"
    required: false
  repo-username:
    description: "The username for the maven repository"
    required: false
  repo-password:
    description: "The password for the maven repository"
    required: false
  gradle-cache-encryption-key:
    description: "The encryption key for the gradle cache"
    required: false
runs:
  using: composite
  steps:
    - uses: silenium-dev/actions/jni-natives/ubuntu@main
      with:
        gradle-cache-encryption-key: ${{ inputs.gradle-cache-encryption-key }}
        snapshot-repo-url: ${{ inputs.snapshot-repo-url }}
        release-repo-url: ${{ inputs.release-repo-url }}
        repo-username: ${{ secrets.REPOSILITE_USERNAME }}
        repo-password: ${{ secrets.REPOSILITE_PASSWORD }}
        tests: false
        java-version: 11
        platform: ${{ github.job }}
        extra-gradle-args: "-Pffmpeg.gpl=${{ matrix.gpl }}"
