name: ffmpeg
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_GCC: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
permissions:
  contents: write
jobs:
#  android-arm:
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-ubuntu
#  android-arm64:
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-ubuntu
#  android-x86:
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-ubuntu
#  android-x86_64:
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-ubuntu
#  linux-armhf:
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-ubuntu
#  linux-arm64:
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-ubuntu
#  linux-ppc64le:
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-ubuntu
#  linux-x86:
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-ubuntu
  linux-x86_64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ext: ["", -gpl]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-ubuntu
        with:
          gradle-cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
#  macosx-arm64:
#    runs-on: macos-12
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-macosx
#  macosx-x86_64:
#    runs-on: macos-12
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-macosx
#  windows-x86:
#    runs-on: windows-2019
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-windows
#  windows-x86_64:
#    runs-on: windows-2019
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/deploy-windows
#  redeploy:
#    needs: [android-arm, android-arm64, android-x86, android-x86_64, linux-armhf, linux-arm64, linux-ppc64le, linux-x86, linux-x86_64, macosx-arm64, macosx-x86_64, windows-x86, windows-x86_64]
#    needs: [android-arm64, android-x86_64, linux-arm64, linux-ppc64le, linux-x86_64, macosx-arm64, macosx-x86_64, windows-x86_64]
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/redeploy
